### PR TITLE
Add another solution to distance-to-zero.

### PR DESCRIPTION
**Pull request by madrury**
Another solution to the distance to zero problem.  This uses a group by.  I think this one is more clear than the other two, but that could certainly just be to me.

### CODE REVIEW

**Comment by ajcr** [comment]
Thank you - more alternatives solutions are definitely a good thing. I can see this approach being more intuitive to people, too.

I think that it's possible to simplify the first two lines to a single line using `cumcount()`:

```
df['Y'] = df.groupby((df['X'] == 0).cumsum()).cumcount()
```

This is probably more idiomatic than using the `lambda`/`transform` combination (but let me know if I've overlooked anything) - are you happy to make this change and then I'll merge?

**Comment by madrury-galvanize** [comment]
Ah!  Good tip on the `cumcount`!  I'll make the change after work and send your way to merge.

**Comment by madrury** [comment]
Ok, change made.

**Comment by ajcr** [comment]
Thank you very much!

**Pull request merged**
