### PR TITLE
Patch: Add non-ix alternative solution to Puzzle 8 

### PR DESCRIPTION
**Pull request by xonoma**

### CODE REVIEW

**Comment by ajcr** [comment]
Thanks! This solution does need to be fixed following the deprecation of `ix`.

Your proposed code works, but chaining indexing operations in pandas is generally discouraged. I think we should go with one of the alternatives for `ix` that's mentioned in the [docs](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#deprecate-ix). Probably this one:

```python
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]
```

We can just delete the `ix` solution since it will soon be gone for good.

Do you want to make these changes to the pull request and then I'll merge?

**Comment by xonoma** [comment]
Still figuring out how to use Github properly, and I hope I've done it right. I've made the necessary changes to the patch branch.

**Comment by ajcr** [comment]
That's perfect - I've merged the changes you made. Thank you!

**Comment by xonoma** [comment]
Happy to contribute. Been going through your exercises, they're very helpful. I'll make suggestions if I find anything else.

**Pull request merged**
